# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '**/**.md'
      - 'donation/**'

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
     

      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1.4
      # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze --fatal-infos 

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: dart test --coverage="./coverage"

      - name: Run tests (non-Linux)
        if: runner.os != 'Linux'
        run: dart test

      - name: Install coverage tools (Linux)
        if: runner.os == 'Linux'
        run: dart pub global activate coverage

      - name: Install lcov (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Format coverage and generate lcov (Linux)
        if: runner.os == 'Linux'
        run: dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Remove generated files from lcov (Linux)
        if: runner.os == 'Linux'
        run: lcov --remove ./coverage/lcov.info '*/lib/src/*.g.dart' '*/lib/src/models/drift/*' -o ./coverage/lcov.info

      - name: Upload coverage to Codecov (Linux)
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: osociety/network_tools
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Check Publish Warnings
        run: dart pub publish --dry-run